### ISSUE TITLE
Make the projects more like Fan's upstream ones

### ISSUE THREAD

**Issue by nacho** [hexchat/gtk-win32#20]
Well right now we are basically taking fan's and changing some variables on where it is going to be build the project and installed. Apart from probably changing something else. Why don't we just pick fan's style and we avoid having to maintain forked versions of the projects?

**Comment by bviktor** [comment]
Because it puts everything in one folder. Makes packaging impossible.

**Comment by nacho** [comment]
Adding @fanc999 to the issue

**Comment by Arnavion** [comment]
We don't maintain individual packages any more, so it's definitely an option.

**Comment by Arnavion** [comment]
So I took a stab at seeing what work would be needed to use upstream's project files for two random libraries - glib and atk. The changes we make to the project files for these libraries are:

1. Add /d2Zi+ compiler switch (via importing stack.props)
1. Remove all `<Optimization>` tags and set optimization level via stack.props
1. Override the install directory (GlibEtcInstallRoot)
1. Override DLL names (GlibSeparateVSDllSuffix, AtkSeparateVSDllSuffix)
1. Override path to Python for glib (PythonPath)
1. Fix bugs (eg glib-install.props is missing a file include/gobject/gobjectnotifyqueue.c since 2.42.0)

(1) helps debugging optimized release builds (eg. user dumps), so all project files will atleast need to be import stack.props as they are now.

(2), (3), (4) and (5) are *required,* but they could be put in stack.props instead of the individual project files, provided stack.props is always imported at the end of the file (so that it overrides the properties instead of being overridden itself).

(6) is obviously needed.

So we could make it that the only changes to upstream's project files are from (1) and (6), and (2) to (5) are in stacks.props instead. However this means that the same *number* of project files will need to be modified from upstream (since almost every file imports stack.props).

**Comment by nacho** [comment]
Thanks for looking at this. First I am adding @fanc999 here to point out these issues. Second I do not think this would be a bad thing even if the same project files are shipped since it would imply a less maintenance time.

**Comment by Arnavion** [comment]
No, it'd not be a "less maintenance time." My workflow is to diff glib-(x - 1)'s build/vs12 directory with glib-x's build/vs12 directory and copy over any changes to our own project files. That is, the amount of maintenance for new versions is going to be the same regardless of whether (2) to (5) are in the individual project files or in stack.props, since (2) to (5) are a one-time change.

**Comment by fanc999** [comment]
Hi,

I have incorporated (1) for Visual Studio 2010+ upstream, along with using /MP for all visual studio build versions, and made the fix for (6) upstream (sorry, should have realized this earlier, my fault), for GLib and GTK+ 2.24/3.14/master.  I will do likewise for Pango, ATK and GDK-Pixbuf tomorrow.  Thanks for the suggestions to make the upstream projects better.

For (3) and (5), this is likely something that would depend on one's build environment, so I would leave that out for now; for (4), since the consensus for Visual Studio builds is to include the Visual Studio numerical version in the built DLL, and the software release naming to show only the major release of the software (for historical reasons that was done by the previous MSVC project's maintainer, Tor), I would leave these out from upstream as well.

Thanks for the suggestions though, with blessings.

**Comment by Arnavion** [comment]
Yeah, (2) to (5) are specific to this repository so it wouldn't make sense for upstream to have them.

**Comment by Arnavion** [comment]
As I said in [this comment](https://github.com/hexchat/gtk-win32/issues/20#issuecomment-76355408) there is no improvement to be had here.
