### ISSUE TITLE
Include gtk3

### ISSUE THREAD

**Issue by nacho** [hexchat/gtk-win32#22]
See https://github.com/nice-software/gtk-win32/commit/438ac86a33a766be687e42c5477209282913dd03
and https://github.com/nice-software/gtk-win32/commit/50f6ba53a5a1c0c3243c7d217780697acc3c24be

Although I guess we would need to first fix the build/buildone topic first in order to not pull this requirement for hexchat and also for my  case to not pull gtk2 if I just want gtk3

**Comment by bviktor** [comment]
There's no good reason to have it until we can actually use it. We're not an official gtk-win32 channel, just HexChat. If you want good GTK win32 support, how about complain to them. Maybe sometime they'll realize they shouldn't neglect their biggest user base.

**Comment by nacho** [comment]
@bviktor again see the other issue I opened.

**Comment by bviktor** [comment]
You opened like 10 other issues.

**Comment by nacho** [comment]
Meant this one: https://github.com/hexchat/gtk-win32/issues/18

**Comment by bviktor** [comment]
Cool, and how is that relevant?

**Comment by nacho** [comment]
It is relevant to the fact that you can convert this project in a gtk builder project not only related to hexchat

**Comment by nacho** [comment]
Also this is not a complain as you say. They are proposals, feel free to drop them.

**Comment by bviktor** [comment]
I don't think it's inside the scope of our goals to right all the wrongs the GTK project's doing, but Arnav or someone else may think differently.

**Comment by nacho** [comment]
What are those wrongs?

**Comment by bviktor** [comment]
Atrocious win32 support.

**Comment by nacho** [comment]
Having the fact that I pushed a lot of stuff upstream into gtk3 for win32 I do not see how you comment comes into place.

**Comment by bviktor** [comment]
Then things may have somewhat changed since the last time I checked. The last time I checked (1 year-ish), GTK either failed to build, or crashed during runtime without patching. This was GTK 2.24 though, can't comment on GTK3.

**Comment by nacho** [comment]
gtk3 is in quite a pretty good shape nowadays, as is glib for which we've put quite a bit of stuff also upstream

**Comment by nacho** [comment]
Another thing, I do not want to convert this into a gtk sucks or does not suck discussion. My main point is whether I should fork the project and make my own thing or continue providing patches for the hexchat project and try to make it a bit more generic so it also feeds my needs.

**Comment by nacho** [comment]
Maybe this project is a "Patches not welcomed" one? :)

**Comment by bviktor** [comment]
Disregard my messages, according to project "officials", I'm not part of this project anymore.

**Comment by TingPing** [comment]
@bviktor @Arnavion is basically the only maintainer of this project and you know it. Neither your or my opinions really matter too much as neither of us would be doing the work. Not to say you can't voice your opinion but @nacho should know "this project" isn't just flat turning him down.

**Comment by bviktor** [comment]
@TingPing I didn't turn him down. We were in the middle of a conversation. I said **I can't comment on GTK3**. I even explained **the last time I checked was 1 year ago**. I can't imagine how that's offensive. All I said was that for now, we use GTK2 and it's not evident to provide GTK3 just for the sake of it. For quite a while, GTK2 has been very-very hard to use on Windows so it may not be worth it to have to put twice as much effort into it. And that's not an offense, that's a hard fact. We've been hearing the promises for years how awesome and bug-free GTK 2.24 will be, and what we got instead was a bunch of *different* bugs with each release. Actually, even *you* said just a few weeks ago that GTK3 is so much better than GTK2 on OSX.

I didn't say anywhere, in any way, that nacho is the reason for this, or that the past problems are his fault, or that I blame it on him, or anything like that. That's only in your imagination. Obviously, that wouldn't even make any sense since I knew literally nothing about him and this was the first time I talked to him, so how could I blame him? So your behavior is what I call persecution complex. 

Of course, you have no idea how much time Arnav and others (dare to say, including me) spent on GTK@Windows so far because you practically didn't put any effort into it and have no idea how annoying this can be. Years of work which normally isn't even the task of an application project in the first place. So you obviously can't understand the fact that I'm more than skeptical about such issues. I don't want to depreciate your awesome work on other aspects, I'm just saying that you're clueless about this part.

If nacho was like "Hey, I'm from GNOME, I want to make GTK nice on Windows, let's do this together", that would've been much clearer. Instead, all I saw was a ton of emails about "Hey, I want this, I want that for unexplained reasons" which is less than obvious. I understand you see it from a different perspective coz you already know each other and that you think these are irrelevant to me coz so am I to the project. So that's about it.

Anyway, if you're not interested in me participating in dependency work, then the next time don't tell me the dependency work could use some help. Of course, "next time" is purely theoretical in this context. If you want to expel someone, there may be better ways. But whatever you say, man, you're the boss.

@nacho it's good to see GTK/GNOME is finally willing to improve the Windows situation. I hope it will come to fruition. Good luck.

**Comment by Arnavion** [comment]
There has been no change in the stance over the last year that a) this repository's maintainers don't care to take the burden of supporting anything outside of HexChat, and b) wingtk has no problem with maintaining gtk3 or any other libraries in their fork.
