### ISSUE TITLE
Use Fan's nmake files for harfbuzz

### ISSUE THREAD

**Issue by pbor** [hexchat/gtk-win32#34]
in our gtk3 fork of the gtk-win32 script I updated harfbuzz to the latest version and switched to use Fan's nmake files. This also removes the need to manually install ragel.exe which is a nice side effect.

https://github.com/wingtk/gtk-win32/commit/37c573e96f5fbe60149820d4ae4e13d8cd50bbee

I think the patch should more or less apply to the upstream version of the script (I guess you may prefer to host the tarball yourselves for consistency with the rest). You may also need yto update to the latest pango which has the MSVC project fixed to look for the harfbuzz headers in the right place (patch is also available in the fork, but that is pretty mechanic to redo)

**Comment by Arnavion** [comment]
Where did you get Fan's nmake file from?

**Comment by pbor** [comment]
It is linked from here

https://github.com/behdad/harfbuzz/pull/164

I am hopeful that the PR will be included soon (Behdad already reviewed and agreed)

**Comment by TingPing** [comment]
On a related note how experimental is the directwrite backend?

**Comment by fanc999** [comment]
Hi,

See:
https://github.com/behdad/harfbuzz/pull/134

**Comment by Arnavion** [comment]
All our hosted source tarballs are identical to upstream's currently, and any changes are present in this repository. So I don't want to combine the PR with upstream's tarball into our own tarball, and I also don't want to put the PR as a patch in this repo because of how big it is.

I'll wait for it to be merged and released.
